pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "weizhi-android"
include(":weizhi")
include(":caps")
include(":agent-tools")
include(":agent-tools-webview")
include(":agent-tools-mcp")
include(":app")
