#!/usr/bin/env python3
"""Minimal Weizhi plugin IDL → C header + manifest.json + agent snippet."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

FN_RE = re.compile(
    r"^fn\s+(\w+)\s*\((.*)\)\s*->\s*([\w]+(?:\([^)]*\))?)\s*$"
)
CB_RE = re.compile(r"^cb\((.*)\)$")
ARG_RE = re.compile(r"(\w+)\s*:\s*([\w]+(?:\([^)]*\))?)")


def parse_idl(text: str) -> dict:
    plugin = None
    version = "0.0.0"
    min_host_abi = 1
    exports = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("plugin "):
            plugin = line.split(None, 1)[1].strip()
            continue
        if line.startswith("version "):
            version = line.split(None, 1)[1].strip()
            continue
        if line.startswith("min_host_abi "):
            min_host_abi = int(line.split(None, 1)[1].strip())
            continue
        m = FN_RE.match(line)
        if not m:
            raise SystemExit(f"bad idl line: {raw}")
        name, args_s, ret = m.group(1), m.group(2).strip(), m.group(3).strip()
        args = []
        if args_s:
            for part in args_s.split(","):
                am = ARG_RE.match(part.strip())
                if not am:
                    raise SystemExit(f"bad arg: {part}")
                args.append({"name": am.group(1), "type": am.group(2)})
        exports.append({"name": name, "args": args, "ret": ret})
    if not plugin:
        raise SystemExit("missing plugin name")
    return {
        "name": plugin,
        "version": version,
        "min_host_abi": min_host_abi,
        "exports": exports,
    }


def c_type(t: str) -> str:
    if t == "i32":
        return "int32_t"
    if t == "i64":
        return "int64_t"
    if t == "f64":
        return "double"
    if t == "bytes":
        return "WeizhiBuf"
    if t == "void":
        return "void"
    if t.startswith("cb("):
        return "uint32_t"  # callback id
    raise SystemExit(f"unsupported type: {t}")


def symbol(plugin: str, fn: str) -> str:
    return f"weizhi_{plugin}_{fn}"


def write_header(meta: dict, out: Path) -> None:
    plugin = meta["name"]
    lines = [
        "/* Generated by scripts/weizhi-bindgen.py — do not edit. */",
        "#ifndef WEIZHI_%s_API_H" % plugin.upper(),
        "#define WEIZHI_%s_API_H" % plugin.upper(),
        "",
        '#include "weizhi_plugin.h"',
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]
    for ex in meta["exports"]:
        ret = c_type(ex["ret"])
        params = []
        for a in ex["args"]:
            params.append(f"{c_type(a['type'])} {a['name']}")
        if not params:
            params = ["void"]
        sym = symbol(plugin, ex["name"])
        lines.append(f"WEIZHI_PLUGIN_EXPORT {ret} {sym}({', '.join(params)});")
    lines += [
        "",
        "/* Optional */",
        "WEIZHI_PLUGIN_EXPORT int weizhi_plugin_init(WeizhiPluginHost *host);",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
        "#endif",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")


def write_manifest(meta: dict, out: Path) -> None:
    plugin = meta["name"]
    exports = []
    for ex in meta["exports"]:
        exports.append(
            {
                "name": ex["name"],
                "symbol": symbol(plugin, ex["name"]),
                "args": [a["type"] for a in ex["args"]],
                "ret": ex["ret"],
            }
        )
    doc = {
        "name": plugin,
        "version": meta["version"],
        "min_host_abi": meta["min_host_abi"],
        "abi": "weizhi_plugin_v1",
        "exports": exports,
    }
    out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")


def write_snippet(meta: dict, out: Path) -> None:
    plugin = meta["name"]
    lines = [
        f"# Agent API: `{plugin}`",
        "",
        f'```js\nconst p = await host.ensureNative("{plugin}");\n```',
        "",
    ]
    for ex in meta["exports"]:
        args = ", ".join(
            f"{a['name']}: {a['type']}" for a in ex["args"]
        )
        lines.append(f"- `p.{ex['name']}({args})` → `{ex['ret']}`")
        if any(a["type"] == "bytes" for a in ex["args"]) or ex["ret"] == "bytes":
            lines.append("  - `bytes` 在 JS 里是 `Buffer`")
        if any(a["type"].startswith("cb(") for a in ex["args"]):
            lines.append("  - 回调参数传 JS `function`，在 C 侧触发时于 JS 线程执行")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("idl", type=Path)
    ap.add_argument("-o", "--outdir", type=Path, required=True)
    args = ap.parse_args()
    meta = parse_idl(args.idl.read_text(encoding="utf-8"))
    args.outdir.mkdir(parents=True, exist_ok=True)
    write_header(meta, args.outdir / f"weizhi_{meta['name']}_api.h")
    write_manifest(meta, args.outdir / "manifest.json")
    write_snippet(meta, args.outdir / "AGENT_SNIPPET.md")
    print(f"wrote {args.outdir} for plugin {meta['name']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
